// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ClaimRepresentation } from './claim-representation';
import { ProtocolMapperRepresentation } from './protocol-mapper-representation';
import { ResourceServerRepresentation } from './resource-server-representation';

/**
 * 
 * @export
 * @interface ApplicationRepresentation
 */
export interface ApplicationRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    rootUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    adminUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    baseUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    surrogateAuthRequired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    alwaysDisplayInConsole?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    clientAuthenticatorType?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    secret?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    registrationAccessToken?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationRepresentation
     */
    defaultRoles?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationRepresentation
     */
    redirectUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationRepresentation
     */
    webOrigins?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ApplicationRepresentation
     */
    notBefore?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    bearerOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    consentRequired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    standardFlowEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    implicitFlowEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    directAccessGrantsEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    serviceAccountsEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    authorizationServicesEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    directGrantsOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    publicClient?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    frontchannelLogout?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    protocol?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationRepresentation
     */
    attributes?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ApplicationRepresentation
     */
    authenticationFlowBindingOverrides?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    fullScopeAllowed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApplicationRepresentation
     */
    nodeReRegistrationTimeout?: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ApplicationRepresentation
     */
    registeredNodes?: { [key: string]: number; };
    /**
     * 
     * @type {Array<ProtocolMapperRepresentation>}
     * @memberof ApplicationRepresentation
     */
    protocolMappers?: Array<ProtocolMapperRepresentation>;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    clientTemplate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    useTemplateConfig?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    useTemplateScope?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationRepresentation
     */
    useTemplateMappers?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationRepresentation
     */
    defaultClientScopes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationRepresentation
     */
    optionalClientScopes?: Array<string>;
    /**
     * 
     * @type {ResourceServerRepresentation}
     * @memberof ApplicationRepresentation
     */
    authorizationSettings?: ResourceServerRepresentation;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof ApplicationRepresentation
     */
    access?: { [key: string]: boolean; };
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    origin?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationRepresentation
     */
    name?: string;
    /**
     * 
     * @type {ClaimRepresentation}
     * @memberof ApplicationRepresentation
     */
    claims?: ClaimRepresentation;
}


