// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticationExecutionExportRepresentation
 */
export interface AuthenticationExecutionExportRepresentation {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionExportRepresentation
     */
    authenticatorConfig?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionExportRepresentation
     */
    authenticator?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExecutionExportRepresentation
     */
    authenticatorFlow?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionExportRepresentation
     */
    requirement?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthenticationExecutionExportRepresentation
     */
    priority?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExecutionExportRepresentation
     */
    autheticatorFlow?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionExportRepresentation
     */
    flowAlias?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExecutionExportRepresentation
     */
    userSetupAllowed?: boolean;
}


