// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AuthenticationExecutionExportRepresentation } from './authentication-execution-export-representation';

/**
 * 
 * @export
 * @interface AuthenticationFlowRepresentation
 */
export interface AuthenticationFlowRepresentation {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationFlowRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationFlowRepresentation
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationFlowRepresentation
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationFlowRepresentation
     */
    providerId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationFlowRepresentation
     */
    topLevel?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationFlowRepresentation
     */
    builtIn?: boolean;
    /**
     * 
     * @type {Array<AuthenticationExecutionExportRepresentation>}
     * @memberof AuthenticationFlowRepresentation
     */
    authenticationExecutions?: Array<AuthenticationExecutionExportRepresentation>;
}


