// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthDetailsRepresentation
 */
export interface AuthDetailsRepresentation {
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsRepresentation
     */
    realmId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsRepresentation
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsRepresentation
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthDetailsRepresentation
     */
    ipAddress?: string;
}


