// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthenticationExecutionInfoRepresentation
 */
export interface AuthenticationExecutionInfoRepresentation {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    requirement?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    requirementChoices?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    configurable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    authenticationFlow?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    providerId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    authenticationConfig?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    flowId?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    level?: number;
    /**
     * 
     * @type {number}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof AuthenticationExecutionInfoRepresentation
     */
    priority?: number;
}


