// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CertificateRepresentation
 */
export interface CertificateRepresentation {
    /**
     * 
     * @type {string}
     * @memberof CertificateRepresentation
     */
    privateKey?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificateRepresentation
     */
    publicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificateRepresentation
     */
    certificate?: string;
    /**
     * 
     * @type {string}
     * @memberof CertificateRepresentation
     */
    kid?: string;
}


