// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClaimRepresentation
 */
export interface ClaimRepresentation {
    /**
     * 
     * @type {boolean}
     * @memberof ClaimRepresentation
     */
    name?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClaimRepresentation
     */
    username?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClaimRepresentation
     */
    profile?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClaimRepresentation
     */
    picture?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClaimRepresentation
     */
    website?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClaimRepresentation
     */
    email?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClaimRepresentation
     */
    gender?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClaimRepresentation
     */
    locale?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClaimRepresentation
     */
    address?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClaimRepresentation
     */
    phone?: boolean;
}


