// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ClientTypeRepresentation } from './client-type-representation';

/**
 * 
 * @export
 * @interface ClientTypesRepresentation
 */
export interface ClientTypesRepresentation {
    /**
     * 
     * @type {Array<ClientTypeRepresentation>}
     * @memberof ClientTypesRepresentation
     */
    client_types?: Array<ClientTypeRepresentation>;
    /**
     * 
     * @type {Array<ClientTypeRepresentation>}
     * @memberof ClientTypesRepresentation
     */
    global_client_types?: Array<ClientTypeRepresentation>;
}


