// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ClientPolicyConditionRepresentation } from './client-policy-condition-representation';

/**
 * 
 * @export
 * @interface ClientPolicyRepresentation
 */
export interface ClientPolicyRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ClientPolicyRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPolicyRepresentation
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ClientPolicyRepresentation
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<ClientPolicyConditionRepresentation>}
     * @memberof ClientPolicyRepresentation
     */
    conditions?: Array<ClientPolicyConditionRepresentation>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ClientPolicyRepresentation
     */
    profiles?: Array<string>;
}


