// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ProtocolMapperRepresentation } from './protocol-mapper-representation';

/**
 * 
 * @export
 * @interface ClientTemplateRepresentation
 */
export interface ClientTemplateRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ClientTemplateRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientTemplateRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientTemplateRepresentation
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientTemplateRepresentation
     */
    protocol?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateRepresentation
     */
    fullScopeAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateRepresentation
     */
    bearerOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateRepresentation
     */
    consentRequired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateRepresentation
     */
    standardFlowEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateRepresentation
     */
    implicitFlowEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateRepresentation
     */
    directAccessGrantsEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateRepresentation
     */
    serviceAccountsEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateRepresentation
     */
    publicClient?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateRepresentation
     */
    frontchannelLogout?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ClientTemplateRepresentation
     */
    attributes?: { [key: string]: string; };
    /**
     * 
     * @type {Array<ProtocolMapperRepresentation>}
     * @memberof ClientTemplateRepresentation
     */
    protocolMappers?: Array<ProtocolMapperRepresentation>;
}


