// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClientInitialAccessPresentation
 */
export interface ClientInitialAccessPresentation {
    /**
     * 
     * @type {string}
     * @memberof ClientInitialAccessPresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientInitialAccessPresentation
     */
    token?: string;
    /**
     * 
     * @type {number}
     * @memberof ClientInitialAccessPresentation
     */
    timestamp?: number;
    /**
     * 
     * @type {number}
     * @memberof ClientInitialAccessPresentation
     */
    expiration?: number;
    /**
     * 
     * @type {number}
     * @memberof ClientInitialAccessPresentation
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof ClientInitialAccessPresentation
     */
    remainingCount?: number;
}


