// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ClientPolicyRepresentation } from './client-policy-representation';

/**
 * 
 * @export
 * @interface ClientPoliciesRepresentation
 */
export interface ClientPoliciesRepresentation {
    /**
     * 
     * @type {Array<ClientPolicyRepresentation>}
     * @memberof ClientPoliciesRepresentation
     */
    policies?: Array<ClientPolicyRepresentation>;
    /**
     * 
     * @type {Array<ClientPolicyRepresentation>}
     * @memberof ClientPoliciesRepresentation
     */
    globalPolicies?: Array<ClientPolicyRepresentation>;
}


