// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PropertyConfig } from './property-config';

/**
 * 
 * @export
 * @interface ClientTypeRepresentation
 */
export interface ClientTypeRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ClientTypeRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientTypeRepresentation
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientTypeRepresentation
     */
    parent?: string;
    /**
     * 
     * @type {{ [key: string]: PropertyConfig; }}
     * @memberof ClientTypeRepresentation
     */
    config?: { [key: string]: PropertyConfig; };
}


