// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RoleRepresentation } from './role-representation';

/**
 * 
 * @export
 * @interface ClientMappingsRepresentation
 */
export interface ClientMappingsRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ClientMappingsRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientMappingsRepresentation
     */
    client?: string;
    /**
     * 
     * @type {Array<RoleRepresentation>}
     * @memberof ClientMappingsRepresentation
     */
    mappings?: Array<RoleRepresentation>;
}


