// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ComponentExportRepresentation } from './component-export-representation';

/**
 * 
 * @export
 * @interface ComponentExportRepresentation
 */
export interface ComponentExportRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ComponentExportRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ComponentExportRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ComponentExportRepresentation
     */
    providerId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComponentExportRepresentation
     */
    subType?: string;
    /**
     * 
     * @type {{ [key: string]: Array<ComponentExportRepresentation>; }}
     * @memberof ComponentExportRepresentation
     */
    subComponents?: { [key: string]: Array<ComponentExportRepresentation>; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ComponentExportRepresentation
     */
    config?: { [key: string]: Array<string>; };
}


