// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ComponentRepresentation
 */
export interface ComponentRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ComponentRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ComponentRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ComponentRepresentation
     */
    providerId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComponentRepresentation
     */
    providerType?: string;
    /**
     * 
     * @type {string}
     * @memberof ComponentRepresentation
     */
    parentId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComponentRepresentation
     */
    subType?: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ComponentRepresentation
     */
    config?: { [key: string]: Array<string>; };
}


