// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Confirmation
 */
export interface Confirmation {
    /**
     * 
     * @type {string}
     * @memberof Confirmation
     */
    x5tS256?: string;
    /**
     * 
     * @type {string}
     * @memberof Confirmation
     */
    jkt?: string;
}


