// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConfigPropertyRepresentation
 */
export interface ConfigPropertyRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ConfigPropertyRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigPropertyRepresentation
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigPropertyRepresentation
     */
    helpText?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigPropertyRepresentation
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigPropertyRepresentation
     */
    defaultValue?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigPropertyRepresentation
     */
    options?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigPropertyRepresentation
     */
    secret?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigPropertyRepresentation
     */
    required?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigPropertyRepresentation
     */
    readOnly?: boolean;
}


