// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CredentialRepresentation
 */
export interface CredentialRepresentation {
    /**
     * 
     * @type {string}
     * @memberof CredentialRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CredentialRepresentation
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CredentialRepresentation
     */
    userLabel?: string;
    /**
     * 
     * @type {number}
     * @memberof CredentialRepresentation
     */
    createdDate?: number;
    /**
     * 
     * @type {string}
     * @memberof CredentialRepresentation
     */
    secretData?: string;
    /**
     * 
     * @type {string}
     * @memberof CredentialRepresentation
     */
    credentialData?: string;
    /**
     * 
     * @type {number}
     * @memberof CredentialRepresentation
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof CredentialRepresentation
     */
    value?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CredentialRepresentation
     */
    temporary?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CredentialRepresentation
     */
    device?: string;
    /**
     * 
     * @type {string}
     * @memberof CredentialRepresentation
     */
    hashedSaltedValue?: string;
    /**
     * 
     * @type {string}
     * @memberof CredentialRepresentation
     */
    salt?: string;
    /**
     * 
     * @type {number}
     * @memberof CredentialRepresentation
     */
    hashIterations?: number;
    /**
     * 
     * @type {number}
     * @memberof CredentialRepresentation
     */
    counter?: number;
    /**
     * 
     * @type {string}
     * @memberof CredentialRepresentation
     */
    algorithm?: string;
    /**
     * 
     * @type {number}
     * @memberof CredentialRepresentation
     */
    digits?: number;
    /**
     * 
     * @type {number}
     * @memberof CredentialRepresentation
     */
    period?: number;
    /**
     * 
     * @type {any}
     * @memberof CredentialRepresentation
     */
    config?: any;
}


