// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ErrorSchema
 * @export
 * @interface ErrorSchema
 */
export interface ErrorSchema {
    /**
     * Code
     * @type {string}
     * @memberof ErrorSchema
     */
    code: string;
    /**
     * Message
     * @type {string}
     * @memberof ErrorSchema
     */
    message: string;
}


