// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EventRepresentation
 */
export interface EventRepresentation {
    /**
     * 
     * @type {number}
     * @memberof EventRepresentation
     */
    time?: number;
    /**
     * 
     * @type {string}
     * @memberof EventRepresentation
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof EventRepresentation
     */
    realmId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventRepresentation
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventRepresentation
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventRepresentation
     */
    sessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventRepresentation
     */
    ipAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof EventRepresentation
     */
    error?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof EventRepresentation
     */
    details?: { [key: string]: string; };
}


