// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupRepresentation
 */
export interface GroupRepresentation {
    /**
     * 
     * @type {string}
     * @memberof GroupRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupRepresentation
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupRepresentation
     */
    parentId?: string;
    /**
     * 
     * @type {number}
     * @memberof GroupRepresentation
     */
    subGroupCount?: number;
    /**
     * 
     * @type {Array<GroupRepresentation>}
     * @memberof GroupRepresentation
     */
    subGroups?: Array<GroupRepresentation>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof GroupRepresentation
     */
    attributes?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupRepresentation
     */
    realmRoles?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof GroupRepresentation
     */
    clientRoles?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof GroupRepresentation
     */
    access?: { [key: string]: boolean; };
}


