// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AddressClaimSet } from './address-claim-set';

/**
 * 
 * @export
 * @interface IdToken
 */
export interface IdToken {
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    jti?: string;
    /**
     * 
     * @type {number}
     * @memberof IdToken
     */
    exp?: number;
    /**
     * 
     * @type {number}
     * @memberof IdToken
     */
    nbf?: number;
    /**
     * 
     * @type {number}
     * @memberof IdToken
     */
    iat?: number;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    iss?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    sub?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    typ?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    azp?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof IdToken
     */
    otherClaims?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    nonce?: string;
    /**
     * 
     * @type {number}
     * @memberof IdToken
     */
    auth_time?: number;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    sid?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    at_hash?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    c_hash?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    given_name?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    family_name?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    middle_name?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    preferred_username?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    profile?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    picture?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IdToken
     */
    email_verified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    birthdate?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    zoneinfo?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    locale?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    phone_number?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IdToken
     */
    phone_number_verified?: boolean;
    /**
     * 
     * @type {AddressClaimSet}
     * @memberof IdToken
     */
    address?: AddressClaimSet;
    /**
     * 
     * @type {number}
     * @memberof IdToken
     */
    updated_at?: number;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    claims_locales?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    acr?: string;
    /**
     * 
     * @type {string}
     * @memberof IdToken
     */
    s_hash?: string;
}


