// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IdentityProviderRepresentation
 */
export interface IdentityProviderRepresentation {
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderRepresentation
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderRepresentation
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderRepresentation
     */
    internalId?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderRepresentation
     */
    providerId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderRepresentation
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderRepresentation
     */
    updateProfileFirstLoginMode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderRepresentation
     */
    trustEmail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderRepresentation
     */
    storeToken?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderRepresentation
     */
    addReadTokenRoleOnCreate?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderRepresentation
     */
    authenticateByDefault?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderRepresentation
     */
    linkOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderRepresentation
     */
    hideOnLogin?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderRepresentation
     */
    firstBrokerLoginFlowAlias?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderRepresentation
     */
    postBrokerLoginFlowAlias?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderRepresentation
     */
    organizationId?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof IdentityProviderRepresentation
     */
    config?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof IdentityProviderRepresentation
     */
    updateProfileFirstLogin?: boolean;
}


