// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IdentityProviderMapperRepresentation
 */
export interface IdentityProviderMapperRepresentation {
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderMapperRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderMapperRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderMapperRepresentation
     */
    identityProviderAlias?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderMapperRepresentation
     */
    identityProviderMapper?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof IdentityProviderMapperRepresentation
     */
    config?: { [key: string]: string; };
}


