// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ConfigPropertyRepresentation } from './config-property-representation';

/**
 * 
 * @export
 * @interface IdentityProviderMapperTypeRepresentation
 */
export interface IdentityProviderMapperTypeRepresentation {
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderMapperTypeRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderMapperTypeRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderMapperTypeRepresentation
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof IdentityProviderMapperTypeRepresentation
     */
    helpText?: string;
    /**
     * 
     * @type {Array<ConfigPropertyRepresentation>}
     * @memberof IdentityProviderMapperTypeRepresentation
     */
    properties?: Array<ConfigPropertyRepresentation>;
}


