// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PolicyEnforcerConfig } from './policy-enforcer-config';

/**
 * 
 * @export
 * @interface InstallationAdapterConfig
 */
export interface InstallationAdapterConfig {
    /**
     * 
     * @type {string}
     * @memberof InstallationAdapterConfig
     */
    realm?: string;
    /**
     * 
     * @type {string}
     * @memberof InstallationAdapterConfig
     */
    realm_public_key?: string;
    /**
     * 
     * @type {string}
     * @memberof InstallationAdapterConfig
     */
    auth_server_url?: string;
    /**
     * 
     * @type {string}
     * @memberof InstallationAdapterConfig
     */
    ssl_required?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InstallationAdapterConfig
     */
    bearer_only?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InstallationAdapterConfig
     */
    resource?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InstallationAdapterConfig
     */
    public_client?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InstallationAdapterConfig
     */
    verify_token_audience?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof InstallationAdapterConfig
     */
    credentials?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof InstallationAdapterConfig
     */
    use_resource_role_mappings?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InstallationAdapterConfig
     */
    confidential_port?: number;
    /**
     * 
     * @type {PolicyEnforcerConfig}
     * @memberof InstallationAdapterConfig
     */
    policy_enforcer?: PolicyEnforcerConfig;
}


