// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { KeyUse } from './key-use';

/**
 * 
 * @export
 * @interface KeyMetadataRepresentation
 */
export interface KeyMetadataRepresentation {
    /**
     * 
     * @type {string}
     * @memberof KeyMetadataRepresentation
     */
    providerId?: string;
    /**
     * 
     * @type {number}
     * @memberof KeyMetadataRepresentation
     */
    providerPriority?: number;
    /**
     * 
     * @type {string}
     * @memberof KeyMetadataRepresentation
     */
    kid?: string;
    /**
     * 
     * @type {string}
     * @memberof KeyMetadataRepresentation
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof KeyMetadataRepresentation
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof KeyMetadataRepresentation
     */
    algorithm?: string;
    /**
     * 
     * @type {string}
     * @memberof KeyMetadataRepresentation
     */
    publicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof KeyMetadataRepresentation
     */
    certificate?: string;
    /**
     * 
     * @type {KeyUse}
     * @memberof KeyMetadataRepresentation
     */
    use?: KeyUse;
    /**
     * 
     * @type {number}
     * @memberof KeyMetadataRepresentation
     */
    validTo?: number;
}


