// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KeyStoreConfig
 */
export interface KeyStoreConfig {
    /**
     * 
     * @type {boolean}
     * @memberof KeyStoreConfig
     */
    realmCertificate?: boolean;
    /**
     * 
     * @type {string}
     * @memberof KeyStoreConfig
     */
    storePassword?: string;
    /**
     * 
     * @type {string}
     * @memberof KeyStoreConfig
     */
    keyPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof KeyStoreConfig
     */
    keyAlias?: string;
    /**
     * 
     * @type {string}
     * @memberof KeyStoreConfig
     */
    realmAlias?: string;
    /**
     * 
     * @type {string}
     * @memberof KeyStoreConfig
     */
    format?: string;
}


