// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ManagementPermissionReference
 */
export interface ManagementPermissionReference {
    /**
     * 
     * @type {boolean}
     * @memberof ManagementPermissionReference
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ManagementPermissionReference
     */
    resource?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ManagementPermissionReference
     */
    scopePermissions?: { [key: string]: string; };
}


