// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CredentialRepresentation } from './credential-representation';
import { FederatedIdentityRepresentation } from './federated-identity-representation';
import { MembershipType } from './membership-type';
import { SocialLinkRepresentation } from './social-link-representation';
import { UserConsentRepresentation } from './user-consent-representation';
import { UserProfileMetadata } from './user-profile-metadata';

/**
 * 
 * @export
 * @interface MemberRepresentation
 */
export interface MemberRepresentation {
    /**
     * 
     * @type {string}
     * @memberof MemberRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberRepresentation
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberRepresentation
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberRepresentation
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberRepresentation
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MemberRepresentation
     */
    emailVerified?: boolean;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof MemberRepresentation
     */
    attributes?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {UserProfileMetadata}
     * @memberof MemberRepresentation
     */
    userProfileMetadata?: UserProfileMetadata;
    /**
     * 
     * @type {string}
     * @memberof MemberRepresentation
     */
    self?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberRepresentation
     */
    origin?: string;
    /**
     * 
     * @type {number}
     * @memberof MemberRepresentation
     */
    createdTimestamp?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MemberRepresentation
     */
    enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberRepresentation
     */
    totp?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MemberRepresentation
     */
    federationLink?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberRepresentation
     */
    serviceAccountClientId?: string;
    /**
     * 
     * @type {Array<CredentialRepresentation>}
     * @memberof MemberRepresentation
     */
    credentials?: Array<CredentialRepresentation>;
    /**
     * 
     * @type {Array<string>}
     * @memberof MemberRepresentation
     */
    disableableCredentialTypes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof MemberRepresentation
     */
    requiredActions?: Array<string>;
    /**
     * 
     * @type {Array<FederatedIdentityRepresentation>}
     * @memberof MemberRepresentation
     */
    federatedIdentities?: Array<FederatedIdentityRepresentation>;
    /**
     * 
     * @type {Array<string>}
     * @memberof MemberRepresentation
     */
    realmRoles?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof MemberRepresentation
     */
    clientRoles?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Array<UserConsentRepresentation>}
     * @memberof MemberRepresentation
     */
    clientConsents?: Array<UserConsentRepresentation>;
    /**
     * 
     * @type {number}
     * @memberof MemberRepresentation
     */
    notBefore?: number;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof MemberRepresentation
     */
    applicationRoles?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Array<SocialLinkRepresentation>}
     * @memberof MemberRepresentation
     */
    socialLinks?: Array<SocialLinkRepresentation>;
    /**
     * 
     * @type {Array<string>}
     * @memberof MemberRepresentation
     */
    groups?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof MemberRepresentation
     */
    access?: { [key: string]: boolean; };
    /**
     * 
     * @type {MembershipType}
     * @memberof MemberRepresentation
     */
    membershipType?: MembershipType;
}


