// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * MeterReqSchema
 * @export
 * @interface MeterReqSchema
 */
export interface MeterReqSchema {
    /**
     * Serial
     * @type {string}
     * @memberof MeterReqSchema
     */
    serial: string;
    /**
     * Type
     * @type {string}
     * @memberof MeterReqSchema
     */
    type: MeterReqSchemaTypeEnum;
    /**
     * Flow Direction
     * @type {number}
     * @memberof MeterReqSchema
     */
    flow_direction: number;
    /**
     * Active
     * @type {boolean}
     * @memberof MeterReqSchema
     */
    active?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum MeterReqSchemaTypeEnum {
    Iot = 'iot',
    Manual = 'manual'
}



