// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MeterReqSchema } from './meter-req-schema';

/**
 * MeterImportReqSchema
 * @export
 * @interface MeterImportReqSchema
 */
export interface MeterImportReqSchema {
    /**
     * Count
     * @type {number}
     * @memberof MeterImportReqSchema
     */
    count: number;
    /**
     * Data
     * @type {Array<MeterReqSchema>}
     * @memberof MeterImportReqSchema
     */
    data: Array<MeterReqSchema>;
}


