// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';

/**
 * MeterResSchema
 * @export
 * @interface MeterResSchema
 */
export interface MeterResSchema {
    /**
     * Serial
     * @type {string}
     * @memberof MeterResSchema
     */
    serial: string;
    /**
     * Type
     * @type {string}
     * @memberof MeterResSchema
     */
    type: MeterResSchemaTypeEnum;
    /**
     * Flow Direction
     * @type {number}
     * @memberof MeterResSchema
     */
    flow_direction: number;
    /**
     * Active
     * @type {boolean}
     * @memberof MeterResSchema
     */
    active?: boolean;
    /**
     * Id
     * @type {string}
     * @memberof MeterResSchema
     */
    id: string;
    /**
     * Tenant Id
     * @type {string | Null}
     * @memberof MeterResSchema
     */
    tenant_id?: string | Null;
    /**
     * Vendor Id
     * @type {string | Null}
     * @memberof MeterResSchema
     */
    vendor_id?: string | Null;
    /**
     * Created Ts
     * @type {string}
     * @memberof MeterResSchema
     */
    created_ts: string;
    /**
     * Updated Ts
     * @type {string}
     * @memberof MeterResSchema
     */
    updated_ts: string;
}

/**
    * @export
    * @enum {string}
    */
export enum MeterResSchemaTypeEnum {
    Iot = 'iot',
    Manual = 'manual'
}



