// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MeterResSchema } from './meter-res-schema';

/**
 * MeterListResSchema
 * @export
 * @interface MeterListResSchema
 */
export interface MeterListResSchema {
    /**
     * Count
     * @type {number}
     * @memberof MeterListResSchema
     */
    count: number;
    /**
     * Data
     * @type {Array<MeterResSchema>}
     * @memberof MeterListResSchema
     */
    data: Array<MeterResSchema>;
}


