// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ScopeEnforcementMode } from './scope-enforcement-mode';

/**
 * 
 * @export
 * @interface MethodConfig
 */
export interface MethodConfig {
    /**
     * 
     * @type {string}
     * @memberof MethodConfig
     */
    method?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MethodConfig
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {ScopeEnforcementMode}
     * @memberof MethodConfig
     */
    scopes_enforcement_mode?: ScopeEnforcementMode;
}


