// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { IdentityProviderRepresentation } from './identity-provider-representation';
import { MemberRepresentation } from './member-representation';
import { OrganizationDomainRepresentation } from './organization-domain-representation';

/**
 * 
 * @export
 * @interface OrganizationRepresentation
 */
export interface OrganizationRepresentation {
    /**
     * 
     * @type {string}
     * @memberof OrganizationRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRepresentation
     */
    alias?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationRepresentation
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRepresentation
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationRepresentation
     */
    redirectUrl?: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof OrganizationRepresentation
     */
    attributes?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Array<OrganizationDomainRepresentation>}
     * @memberof OrganizationRepresentation
     */
    domains?: Array<OrganizationDomainRepresentation>;
    /**
     * 
     * @type {Array<MemberRepresentation>}
     * @memberof OrganizationRepresentation
     */
    members?: Array<MemberRepresentation>;
    /**
     * 
     * @type {Array<IdentityProviderRepresentation>}
     * @memberof OrganizationRepresentation
     */
    identityProviders?: Array<IdentityProviderRepresentation>;
}


