// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EnforcementMode } from './enforcement-mode';
import { MethodConfig } from './method-config';

/**
 * 
 * @export
 * @interface PathConfig
 */
export interface PathConfig {
    /**
     * 
     * @type {string}
     * @memberof PathConfig
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PathConfig
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof PathConfig
     */
    path?: string;
    /**
     * 
     * @type {Array<MethodConfig>}
     * @memberof PathConfig
     */
    methods?: Array<MethodConfig>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PathConfig
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PathConfig
     */
    id?: string;
    /**
     * 
     * @type {EnforcementMode}
     * @memberof PathConfig
     */
    enforcement_mode?: EnforcementMode;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof PathConfig
     */
    claim_information_point?: { [key: string]: { [key: string]: string; }; };
    /**
     * 
     * @type {boolean}
     * @memberof PathConfig
     */
    invalidated?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PathConfig
     */
    staticPath?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PathConfig
     */
    _static?: boolean;
}


