// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Permission
 */
export interface Permission {
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    rsid?: string;
    /**
     * 
     * @type {string}
     * @memberof Permission
     */
    rsname?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Permission
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Permission
     */
    claims?: { [key: string]: Array<string>; };
}


