// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Category } from './category';
import { Tag } from './tag';

/**
 * 
 * @export
 * @interface Pet
 */
export interface Pet {
    /**
     * Pet ID
     * @type {number}
     * @memberof Pet
     */
    id: number;
    /**
     * 
     * @type {Category}
     * @memberof Pet
     */
    category: Category;
    /**
     * name
     * @type {string}
     * @memberof Pet
     */
    name: string;
    /**
     * image URL
     * @type {Array<string>}
     * @memberof Pet
     */
    photoUrls: Array<string>;
    /**
     * tag
     * @type {Array<Tag>}
     * @memberof Pet
     */
    tags: Array<Tag>;
    /**
     * Pet Sales Status
     * @type {string}
     * @memberof Pet
     */
    status: PetStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum PetStatusEnum {
    Available = 'available',
    Pending = 'pending',
    Sold = 'sold'
}



