// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProtocolMapperRepresentation
 */
export interface ProtocolMapperRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ProtocolMapperRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProtocolMapperRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProtocolMapperRepresentation
     */
    protocol?: string;
    /**
     * 
     * @type {string}
     * @memberof ProtocolMapperRepresentation
     */
    protocolMapper?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProtocolMapperRepresentation
     */
    consentRequired?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProtocolMapperRepresentation
     */
    consentText?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ProtocolMapperRepresentation
     */
    config?: { [key: string]: string; };
}


