// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PublishedRealmRepresentation
 */
export interface PublishedRealmRepresentation {
    /**
     * 
     * @type {string}
     * @memberof PublishedRealmRepresentation
     */
    realm?: string;
    /**
     * 
     * @type {string}
     * @memberof PublishedRealmRepresentation
     */
    public_key?: string;
    /**
     * 
     * @type {string}
     * @memberof PublishedRealmRepresentation
     */
    token_service?: string;
    /**
     * 
     * @type {string}
     * @memberof PublishedRealmRepresentation
     */
    account_service?: string;
    /**
     * 
     * @type {number}
     * @memberof PublishedRealmRepresentation
     */
    tokens_not_before?: number;
}


