// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RealmEventsConfigRepresentation
 */
export interface RealmEventsConfigRepresentation {
    /**
     * 
     * @type {boolean}
     * @memberof RealmEventsConfigRepresentation
     */
    eventsEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RealmEventsConfigRepresentation
     */
    eventsExpiration?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmEventsConfigRepresentation
     */
    eventsListeners?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmEventsConfigRepresentation
     */
    enabledEventTypes?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof RealmEventsConfigRepresentation
     */
    adminEventsEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmEventsConfigRepresentation
     */
    adminEventsDetailsEnabled?: boolean;
}


