// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApplicationRepresentation } from './application-representation';
import { AuthenticationFlowRepresentation } from './authentication-flow-representation';
import { AuthenticatorConfigRepresentation } from './authenticator-config-representation';
import { BruteForceStrategy } from './brute-force-strategy';
import { ClientPoliciesRepresentation } from './client-policies-representation';
import { ClientProfilesRepresentation } from './client-profiles-representation';
import { ClientRepresentation } from './client-representation';
import { ClientScopeRepresentation } from './client-scope-representation';
import { ClientTemplateRepresentation } from './client-template-representation';
import { ComponentExportRepresentation } from './component-export-representation';
import { GroupRepresentation } from './group-representation';
import { IdentityProviderMapperRepresentation } from './identity-provider-mapper-representation';
import { IdentityProviderRepresentation } from './identity-provider-representation';
import { OAuthClientRepresentation } from './oauth-client-representation';
import { OrganizationRepresentation } from './organization-representation';
import { ProtocolMapperRepresentation } from './protocol-mapper-representation';
import { RequiredActionProviderRepresentation } from './required-action-provider-representation';
import { RoleRepresentation } from './role-representation';
import { RolesRepresentation } from './roles-representation';
import { ScopeMappingRepresentation } from './scope-mapping-representation';
import { UserFederationMapperRepresentation } from './user-federation-mapper-representation';
import { UserFederationProviderRepresentation } from './user-federation-provider-representation';
import { UserRepresentation } from './user-representation';

/**
 * 
 * @export
 * @interface RealmRepresentation
 */
export interface RealmRepresentation {
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    realm?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    displayNameHtml?: string;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    notBefore?: number;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    defaultSignatureAlgorithm?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    revokeRefreshToken?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    refreshTokenMaxReuse?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    accessTokenLifespan?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    accessTokenLifespanForImplicitFlow?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    ssoSessionIdleTimeout?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    ssoSessionMaxLifespan?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    ssoSessionIdleTimeoutRememberMe?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    ssoSessionMaxLifespanRememberMe?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    offlineSessionIdleTimeout?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    offlineSessionMaxLifespanEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    offlineSessionMaxLifespan?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    clientSessionIdleTimeout?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    clientSessionMaxLifespan?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    clientOfflineSessionIdleTimeout?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    clientOfflineSessionMaxLifespan?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    accessCodeLifespan?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    accessCodeLifespanUserAction?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    accessCodeLifespanLogin?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    actionTokenGeneratedByAdminLifespan?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    actionTokenGeneratedByUserLifespan?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    oauth2DeviceCodeLifespan?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    oauth2DevicePollingInterval?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    sslRequired?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    passwordCredentialGrantAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    registrationAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    registrationEmailAsUsername?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    rememberMe?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    verifyEmail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    loginWithEmailAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    duplicateEmailsAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    resetPasswordAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    editUsernameAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    userCacheEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    realmCacheEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    bruteForceProtected?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    permanentLockout?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    maxTemporaryLockouts?: number;
    /**
     * 
     * @type {BruteForceStrategy}
     * @memberof RealmRepresentation
     */
    bruteForceStrategy?: BruteForceStrategy;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    maxFailureWaitSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    minimumQuickLoginWaitSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    waitIncrementSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    quickLoginCheckMilliSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    maxDeltaTimeSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    failureFactor?: number;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    privateKey?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    publicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    certificate?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    codeSecret?: string;
    /**
     * 
     * @type {RolesRepresentation}
     * @memberof RealmRepresentation
     */
    roles?: RolesRepresentation;
    /**
     * 
     * @type {Array<GroupRepresentation>}
     * @memberof RealmRepresentation
     */
    groups?: Array<GroupRepresentation>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    defaultRoles?: Array<string>;
    /**
     * 
     * @type {RoleRepresentation}
     * @memberof RealmRepresentation
     */
    defaultRole?: RoleRepresentation;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    defaultGroups?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    requiredCredentials?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    passwordPolicy?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    otpPolicyType?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    otpPolicyAlgorithm?: string;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    otpPolicyInitialCounter?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    otpPolicyDigits?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    otpPolicyLookAheadWindow?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    otpPolicyPeriod?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    otpPolicyCodeReusable?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    otpSupportedApplications?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof RealmRepresentation
     */
    localizationTexts?: { [key: string]: { [key: string]: string; }; };
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyRpEntityName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    webAuthnPolicySignatureAlgorithms?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyRpId?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyAttestationConveyancePreference?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyAuthenticatorAttachment?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyRequireResidentKey?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyUserVerificationRequirement?: string;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyCreateTimeout?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyAvoidSameAuthenticatorRegister?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyAcceptableAaguids?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyExtraOrigins?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessRpEntityName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessSignatureAlgorithms?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessRpId?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessAttestationConveyancePreference?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessAuthenticatorAttachment?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessRequireResidentKey?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessUserVerificationRequirement?: string;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessCreateTimeout?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessAcceptableAaguids?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    webAuthnPolicyPasswordlessExtraOrigins?: Array<string>;
    /**
     * 
     * @type {ClientProfilesRepresentation}
     * @memberof RealmRepresentation
     */
    clientProfiles?: ClientProfilesRepresentation;
    /**
     * 
     * @type {ClientPoliciesRepresentation}
     * @memberof RealmRepresentation
     */
    clientPolicies?: ClientPoliciesRepresentation;
    /**
     * 
     * @type {Array<UserRepresentation>}
     * @memberof RealmRepresentation
     */
    users?: Array<UserRepresentation>;
    /**
     * 
     * @type {Array<UserRepresentation>}
     * @memberof RealmRepresentation
     */
    federatedUsers?: Array<UserRepresentation>;
    /**
     * 
     * @type {Array<ScopeMappingRepresentation>}
     * @memberof RealmRepresentation
     */
    scopeMappings?: Array<ScopeMappingRepresentation>;
    /**
     * 
     * @type {{ [key: string]: Array<ScopeMappingRepresentation>; }}
     * @memberof RealmRepresentation
     */
    clientScopeMappings?: { [key: string]: Array<ScopeMappingRepresentation>; };
    /**
     * 
     * @type {Array<ClientRepresentation>}
     * @memberof RealmRepresentation
     */
    clients?: Array<ClientRepresentation>;
    /**
     * 
     * @type {Array<ClientScopeRepresentation>}
     * @memberof RealmRepresentation
     */
    clientScopes?: Array<ClientScopeRepresentation>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    defaultDefaultClientScopes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    defaultOptionalClientScopes?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RealmRepresentation
     */
    browserSecurityHeaders?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RealmRepresentation
     */
    smtpServer?: { [key: string]: string; };
    /**
     * 
     * @type {Array<UserFederationProviderRepresentation>}
     * @memberof RealmRepresentation
     */
    userFederationProviders?: Array<UserFederationProviderRepresentation>;
    /**
     * 
     * @type {Array<UserFederationMapperRepresentation>}
     * @memberof RealmRepresentation
     */
    userFederationMappers?: Array<UserFederationMapperRepresentation>;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    loginTheme?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    accountTheme?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    adminTheme?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    emailTheme?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    eventsEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    eventsExpiration?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    eventsListeners?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    enabledEventTypes?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    adminEventsEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    adminEventsDetailsEnabled?: boolean;
    /**
     * 
     * @type {Array<IdentityProviderRepresentation>}
     * @memberof RealmRepresentation
     */
    identityProviders?: Array<IdentityProviderRepresentation>;
    /**
     * 
     * @type {Array<IdentityProviderMapperRepresentation>}
     * @memberof RealmRepresentation
     */
    identityProviderMappers?: Array<IdentityProviderMapperRepresentation>;
    /**
     * 
     * @type {Array<ProtocolMapperRepresentation>}
     * @memberof RealmRepresentation
     */
    protocolMappers?: Array<ProtocolMapperRepresentation>;
    /**
     * 
     * @type {{ [key: string]: Array<ComponentExportRepresentation>; }}
     * @memberof RealmRepresentation
     */
    components?: { [key: string]: Array<ComponentExportRepresentation>; };
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    internationalizationEnabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RealmRepresentation
     */
    supportedLocales?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    defaultLocale?: string;
    /**
     * 
     * @type {Array<AuthenticationFlowRepresentation>}
     * @memberof RealmRepresentation
     */
    authenticationFlows?: Array<AuthenticationFlowRepresentation>;
    /**
     * 
     * @type {Array<AuthenticatorConfigRepresentation>}
     * @memberof RealmRepresentation
     */
    authenticatorConfig?: Array<AuthenticatorConfigRepresentation>;
    /**
     * 
     * @type {Array<RequiredActionProviderRepresentation>}
     * @memberof RealmRepresentation
     */
    requiredActions?: Array<RequiredActionProviderRepresentation>;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    browserFlow?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    registrationFlow?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    directGrantFlow?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    resetCredentialsFlow?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    clientAuthenticationFlow?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    dockerAuthenticationFlow?: string;
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    firstBrokerLoginFlow?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RealmRepresentation
     */
    attributes?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof RealmRepresentation
     */
    keycloakVersion?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    userManagedAccessAllowed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    organizationsEnabled?: boolean;
    /**
     * 
     * @type {Array<OrganizationRepresentation>}
     * @memberof RealmRepresentation
     */
    organizations?: Array<OrganizationRepresentation>;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    social?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RealmRepresentation
     */
    updateProfileOnInitialSocialLogin?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RealmRepresentation
     */
    socialProviders?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: Array<ScopeMappingRepresentation>; }}
     * @memberof RealmRepresentation
     */
    applicationScopeMappings?: { [key: string]: Array<ScopeMappingRepresentation>; };
    /**
     * 
     * @type {Array<ApplicationRepresentation>}
     * @memberof RealmRepresentation
     */
    applications?: Array<ApplicationRepresentation>;
    /**
     * 
     * @type {Array<OAuthClientRepresentation>}
     * @memberof RealmRepresentation
     */
    oauthClients?: Array<OAuthClientRepresentation>;
    /**
     * 
     * @type {Array<ClientTemplateRepresentation>}
     * @memberof RealmRepresentation
     */
    clientTemplates?: Array<ClientTemplateRepresentation>;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    oAuth2DeviceCodeLifespan?: number;
    /**
     * 
     * @type {number}
     * @memberof RealmRepresentation
     */
    oAuth2DevicePollingInterval?: number;
}


