// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SourceReqSchema } from './source-req-schema';
import { TenantReqSchema } from './tenant-req-schema';
import { UnitReqSchema } from './unit-req-schema';
import { UserReqSchema } from './user-req-schema';
import { VendorReqSchema } from './vendor-req-schema';

/**
 * RequestSchema
 * @export
 * @interface RequestSchema
 */
export interface RequestSchema {
    /**
     * Data
     * @type {TenantReqSchema | UserReqSchema | VendorReqSchema | SourceReqSchema | UnitReqSchema}
     * @memberof RequestSchema
     */
    data: TenantReqSchema | UserReqSchema | VendorReqSchema | SourceReqSchema | UnitReqSchema;
}


