// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DecisionStrategy } from './decision-strategy';
import { PolicyEnforcementMode } from './policy-enforcement-mode';
import { PolicyRepresentation } from './policy-representation';
import { ResourceRepresentation } from './resource-representation';
import { ScopeRepresentation } from './scope-representation';

/**
 * 
 * @export
 * @interface ResourceServerRepresentation
 */
export interface ResourceServerRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ResourceServerRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceServerRepresentation
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceServerRepresentation
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceServerRepresentation
     */
    allowRemoteResourceManagement?: boolean;
    /**
     * 
     * @type {PolicyEnforcementMode}
     * @memberof ResourceServerRepresentation
     */
    policyEnforcementMode?: PolicyEnforcementMode;
    /**
     * 
     * @type {Array<ResourceRepresentation>}
     * @memberof ResourceServerRepresentation
     */
    resources?: Array<ResourceRepresentation>;
    /**
     * 
     * @type {Array<PolicyRepresentation>}
     * @memberof ResourceServerRepresentation
     */
    policies?: Array<PolicyRepresentation>;
    /**
     * 
     * @type {Array<ScopeRepresentation>}
     * @memberof ResourceServerRepresentation
     */
    scopes?: Array<ScopeRepresentation>;
    /**
     * 
     * @type {DecisionStrategy}
     * @memberof ResourceServerRepresentation
     */
    decisionStrategy?: DecisionStrategy;
}


