// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ErrorSchema } from './error-schema';
import { Null } from './null';

/**
 * ResponseSchema
 * @export
 * @interface ResponseSchema
 */
export interface ResponseSchema {
    /**
     * Status
     * @type {string}
     * @memberof ResponseSchema
     */
    status?: string;
    /**
     * 
     * @type {ErrorSchema | Null}
     * @memberof ResponseSchema
     */
    data: ErrorSchema | Null;
}


