// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Composites } from './composites';

/**
 * 
 * @export
 * @interface RoleRepresentation
 */
export interface RoleRepresentation {
    /**
     * 
     * @type {string}
     * @memberof RoleRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRepresentation
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RoleRepresentation
     */
    scopeParamRequired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RoleRepresentation
     */
    composite?: boolean;
    /**
     * 
     * @type {Composites}
     * @memberof RoleRepresentation
     */
    composites?: Composites;
    /**
     * 
     * @type {boolean}
     * @memberof RoleRepresentation
     */
    clientRole?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RoleRepresentation
     */
    containerId?: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof RoleRepresentation
     */
    attributes?: { [key: string]: Array<string>; };
}


