// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PolicyRepresentation } from './policy-representation';
import { ResourceRepresentation } from './resource-representation';

/**
 * 
 * @export
 * @interface ScopeRepresentation
 */
export interface ScopeRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ScopeRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ScopeRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ScopeRepresentation
     */
    iconUri?: string;
    /**
     * 
     * @type {Array<PolicyRepresentation>}
     * @memberof ScopeRepresentation
     */
    policies?: Array<PolicyRepresentation>;
    /**
     * 
     * @type {Array<ResourceRepresentation>}
     * @memberof ScopeRepresentation
     */
    resources?: Array<ResourceRepresentation>;
    /**
     * 
     * @type {string}
     * @memberof ScopeRepresentation
     */
    displayName?: string;
}


