// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScopeMappingRepresentation
 */
export interface ScopeMappingRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ScopeMappingRepresentation
     */
    self?: string;
    /**
     * 
     * @type {string}
     * @memberof ScopeMappingRepresentation
     */
    client?: string;
    /**
     * 
     * @type {string}
     * @memberof ScopeMappingRepresentation
     */
    clientTemplate?: string;
    /**
     * 
     * @type {string}
     * @memberof ScopeMappingRepresentation
     */
    clientScope?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScopeMappingRepresentation
     */
    roles?: Array<string>;
}


