// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * SourceResSchema
 * @export
 * @interface SourceResSchema
 */
export interface SourceResSchema {
    /**
     * Category
     * @type {number}
     * @memberof SourceResSchema
     */
    category: number;
    /**
     * Tag
     * @type {string}
     * @memberof SourceResSchema
     */
    tag: string;
    /**
     * Active
     * @type {boolean}
     * @memberof SourceResSchema
     */
    active?: boolean;
    /**
     * Id
     * @type {string}
     * @memberof SourceResSchema
     */
    id: string;
    /**
     * Created Ts
     * @type {string}
     * @memberof SourceResSchema
     */
    created_ts: string;
    /**
     * Updated Ts
     * @type {string}
     * @memberof SourceResSchema
     */
    updated_ts: string;
}


