// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SourceReqSchema } from './source-req-schema';

/**
 * SourceImportReqSchema
 * @export
 * @interface SourceImportReqSchema
 */
export interface SourceImportReqSchema {
    /**
     * Count
     * @type {number}
     * @memberof SourceImportReqSchema
     */
    count: number;
    /**
     * Data
     * @type {Array<SourceReqSchema>}
     * @memberof SourceImportReqSchema
     */
    data: Array<SourceReqSchema>;
}


