// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * SourceReqSchema
 * @export
 * @interface SourceReqSchema
 */
export interface SourceReqSchema {
    /**
     * Category
     * @type {number}
     * @memberof SourceReqSchema
     */
    category: number;
    /**
     * Tag
     * @type {string}
     * @memberof SourceReqSchema
     */
    tag: string;
    /**
     * Active
     * @type {boolean}
     * @memberof SourceReqSchema
     */
    active?: boolean;
}


