// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * StatusResSchema
 * @export
 * @interface StatusResSchema
 */
export interface StatusResSchema {
    /**
     * Name
     * @type {string}
     * @memberof StatusResSchema
     */
    name: string;
    /**
     * Version
     * @type {string}
     * @memberof StatusResSchema
     */
    version: string;
}


