// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * StatusVersionResSchema
 * @export
 * @interface StatusVersionResSchema
 */
export interface StatusVersionResSchema {
    /**
     * Name
     * @type {string}
     * @memberof StatusVersionResSchema
     */
    name: string;
    /**
     * Api Version
     * @type {string}
     * @memberof StatusVersionResSchema
     */
    api_version: string;
    /**
     * Source Version
     * @type {string}
     * @memberof StatusVersionResSchema
     */
    source_version: string;
}


