// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * StatusMetricsResSchema
 * @export
 * @interface StatusMetricsResSchema
 */
export interface StatusMetricsResSchema {
    /**
     * Name
     * @type {string}
     * @memberof StatusMetricsResSchema
     */
    name: string;
    /**
     * Api Version
     * @type {string}
     * @memberof StatusMetricsResSchema
     */
    api_version: string;
    /**
     * Source Version
     * @type {string}
     * @memberof StatusMetricsResSchema
     */
    source_version: string;
    /**
     * Path Metrics
     * @type {object}
     * @memberof StatusMetricsResSchema
     */
    path_metrics: object;
    /**
     * Method Metrics
     * @type {object}
     * @memberof StatusMetricsResSchema
     */
    method_metrics: object;
}


