// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TenantResSchema } from './tenant-res-schema';

/**
 * TenantExportResSchema
 * @export
 * @interface TenantExportResSchema
 */
export interface TenantExportResSchema {
    /**
     * Count
     * @type {number}
     * @memberof TenantExportResSchema
     */
    count: number;
    /**
     * Data
     * @type {Array<TenantResSchema>}
     * @memberof TenantExportResSchema
     */
    data: Array<TenantResSchema>;
}


