// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';
import { TenantUsersExtResSchema } from './tenant-users-ext-res-schema';

/**
 * TenantUsersListResSchema
 * @export
 * @interface TenantUsersListResSchema
 */
export interface TenantUsersListResSchema {
    /**
     * Data
     * @type {Array<TenantUsersExtResSchema>}
     * @memberof TenantUsersListResSchema
     */
    data: Array<TenantUsersExtResSchema>;
    /**
     * Count
     * @type {number}
     * @memberof TenantUsersListResSchema
     */
    count: number;
    /**
     * Total Count
     * @type {number | Null}
     * @memberof TenantUsersListResSchema
     */
    total_count?: number | Null;
}


