// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';
import { TenantResSchema } from './tenant-res-schema';

/**
 * TenantListResSchema
 * @export
 * @interface TenantListResSchema
 */
export interface TenantListResSchema {
    /**
     * Data
     * @type {Array<TenantResSchema>}
     * @memberof TenantListResSchema
     */
    data: Array<TenantResSchema>;
    /**
     * Count
     * @type {number}
     * @memberof TenantListResSchema
     */
    count: number;
    /**
     * Total Count
     * @type {number | Null}
     * @memberof TenantListResSchema
     */
    total_count?: number | Null;
}


