// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TenantResSchema
 * @export
 * @interface TenantResSchema
 */
export interface TenantResSchema {
    /**
     * Name
     * @type {string}
     * @memberof TenantResSchema
     */
    name: string;
    /**
     * Address
     * @type {string}
     * @memberof TenantResSchema
     */
    address: string;
    /**
     * Tax Id
     * @type {string}
     * @memberof TenantResSchema
     */
    tax_id: string;
    /**
     * Active
     * @type {boolean}
     * @memberof TenantResSchema
     */
    active?: boolean;
    /**
     * Id
     * @type {string}
     * @memberof TenantResSchema
     */
    id: string;
    /**
     * Created Ts
     * @type {string}
     * @memberof TenantResSchema
     */
    created_ts: string;
    /**
     * Updated Ts
     * @type {string}
     * @memberof TenantResSchema
     */
    updated_ts: string;
}


