// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';

/**
 * TenantVendorsResSchema
 * @export
 * @interface TenantVendorsResSchema
 */
export interface TenantVendorsResSchema {
    /**
     * Contact Fullname
     * @type {string}
     * @memberof TenantVendorsResSchema
     */
    contact_fullname: string;
    /**
     * Contact Mobile
     * @type {string}
     * @memberof TenantVendorsResSchema
     */
    contact_mobile: string;
    /**
     * Contact Email
     * @type {string | Null}
     * @memberof TenantVendorsResSchema
     */
    contact_email: string | Null;
    /**
     * Active
     * @type {boolean}
     * @memberof TenantVendorsResSchema
     */
    active?: boolean;
    /**
     * Tenant Id
     * @type {string}
     * @memberof TenantVendorsResSchema
     */
    tenant_id: string;
    /**
     * Vendor Id
     * @type {string}
     * @memberof TenantVendorsResSchema
     */
    vendor_id: string;
    /**
     * Created Ts
     * @type {string}
     * @memberof TenantVendorsResSchema
     */
    created_ts: string;
    /**
     * Updated Ts
     * @type {string}
     * @memberof TenantVendorsResSchema
     */
    updated_ts: string;
}


