// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TenantReqSchema
 * @export
 * @interface TenantReqSchema
 */
export interface TenantReqSchema {
    /**
     * Name
     * @type {string}
     * @memberof TenantReqSchema
     */
    name: string;
    /**
     * Address
     * @type {string}
     * @memberof TenantReqSchema
     */
    address: string;
    /**
     * Tax Id
     * @type {string}
     * @memberof TenantReqSchema
     */
    tax_id: string;
    /**
     * Active
     * @type {boolean}
     * @memberof TenantReqSchema
     */
    active?: boolean;
}


