// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TenantUsersResSchema
 * @export
 * @interface TenantUsersResSchema
 */
export interface TenantUsersResSchema {
    /**
     * Active
     * @type {boolean}
     * @memberof TenantUsersResSchema
     */
    active?: boolean;
    /**
     * Tenant Id
     * @type {string}
     * @memberof TenantUsersResSchema
     */
    tenant_id: string;
    /**
     * User Id
     * @type {string}
     * @memberof TenantUsersResSchema
     */
    user_id: string;
    /**
     * Created Ts
     * @type {string}
     * @memberof TenantUsersResSchema
     */
    created_ts: string;
    /**
     * Updated Ts
     * @type {string}
     * @memberof TenantUsersResSchema
     */
    updated_ts: string;
}


