// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';

/**
 * TenantVendorsReqSchema
 * @export
 * @interface TenantVendorsReqSchema
 */
export interface TenantVendorsReqSchema {
    /**
     * Contact Fullname
     * @type {string}
     * @memberof TenantVendorsReqSchema
     */
    contact_fullname: string;
    /**
     * Contact Mobile
     * @type {string}
     * @memberof TenantVendorsReqSchema
     */
    contact_mobile: string;
    /**
     * Contact Email
     * @type {string | Null}
     * @memberof TenantVendorsReqSchema
     */
    contact_email: string | Null;
    /**
     * Active
     * @type {boolean}
     * @memberof TenantVendorsReqSchema
     */
    active?: boolean;
}


