// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TenantVendorsExtResSchema } from './tenant-vendors-ext-res-schema';

/**
 * TenantVendorsListResSchema
 * @export
 * @interface TenantVendorsListResSchema
 */
export interface TenantVendorsListResSchema {
    /**
     * Data
     * @type {Array<TenantVendorsExtResSchema>}
     * @memberof TenantVendorsListResSchema
     */
    data: Array<TenantVendorsExtResSchema>;
    /**
     * Count
     * @type {number}
     * @memberof TenantVendorsListResSchema
     */
    count: number;
    /**
     * Total Count
     * @type {number}
     * @memberof TenantVendorsListResSchema
     */
    total_count?: number;
}


