// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TenantReqSchema } from './tenant-req-schema';

/**
 * TenantImportReqSchema
 * @export
 * @interface TenantImportReqSchema
 */
export interface TenantImportReqSchema {
    /**
     * Count
     * @type {number}
     * @memberof TenantImportReqSchema
     */
    count: number;
    /**
     * Data
     * @type {Array<TenantReqSchema>}
     * @memberof TenantImportReqSchema
     */
    data: Array<TenantReqSchema>;
}


