// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';

/**
 * UnitResSchema
 * @export
 * @interface UnitResSchema
 */
export interface UnitResSchema {
    /**
     * Tag
     * @type {string}
     * @memberof UnitResSchema
     */
    tag: string;
    /**
     * Category
     * @type {number}
     * @memberof UnitResSchema
     */
    category: number;
    /**
     * Area
     * @type {number | Null}
     * @memberof UnitResSchema
     */
    area: number | Null;
    /**
     * Inlets
     * @type {number}
     * @memberof UnitResSchema
     */
    inlets: number;
    /**
     * Active
     * @type {boolean}
     * @memberof UnitResSchema
     */
    active?: boolean;
    /**
     * Id
     * @type {string}
     * @memberof UnitResSchema
     */
    id: string;
    /**
     * Tenant Id
     * @type {string | Null}
     * @memberof UnitResSchema
     */
    tenant_id?: string | Null;
    /**
     * Primary User Id
     * @type {string | Null}
     * @memberof UnitResSchema
     */
    primary_user_id?: string | Null;
    /**
     * Secondary User Id
     * @type {string | Null}
     * @memberof UnitResSchema
     */
    secondary_user_id?: string | Null;
    /**
     * Created Ts
     * @type {string}
     * @memberof UnitResSchema
     */
    created_ts: string;
    /**
     * Updated Ts
     * @type {string}
     * @memberof UnitResSchema
     */
    updated_ts: string;
}


