// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';

/**
 * UnitReqSchema
 * @export
 * @interface UnitReqSchema
 */
export interface UnitReqSchema {
    /**
     * Tag
     * @type {string}
     * @memberof UnitReqSchema
     */
    tag: string;
    /**
     * Category
     * @type {number}
     * @memberof UnitReqSchema
     */
    category: number;
    /**
     * Area
     * @type {number | Null}
     * @memberof UnitReqSchema
     */
    area: number | Null;
    /**
     * Inlets
     * @type {number}
     * @memberof UnitReqSchema
     */
    inlets: number;
    /**
     * Active
     * @type {boolean}
     * @memberof UnitReqSchema
     */
    active?: boolean;
}


