// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UnitResSchema } from './unit-res-schema';

/**
 * UnitExportResSchema
 * @export
 * @interface UnitExportResSchema
 */
export interface UnitExportResSchema {
    /**
     * Count
     * @type {number}
     * @memberof UnitExportResSchema
     */
    count: number;
    /**
     * Data
     * @type {Array<UnitResSchema>}
     * @memberof UnitExportResSchema
     */
    data: Array<UnitResSchema>;
}


