// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UnitReqSchema } from './unit-req-schema';

/**
 * UnitImportReqSchema
 * @export
 * @interface UnitImportReqSchema
 */
export interface UnitImportReqSchema {
    /**
     * Count
     * @type {number}
     * @memberof UnitImportReqSchema
     */
    count: number;
    /**
     * Data
     * @type {Array<UnitReqSchema>}
     * @memberof UnitImportReqSchema
     */
    data: Array<UnitReqSchema>;
}


