// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UpAttributePermissions } from './up-attribute-permissions';
import { UpAttributeRequired } from './up-attribute-required';
import { UpAttributeSelector } from './up-attribute-selector';

/**
 * 
 * @export
 * @interface UpAttribute
 */
export interface UpAttribute {
    /**
     * 
     * @type {string}
     * @memberof UpAttribute
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpAttribute
     */
    displayName?: string;
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof UpAttribute
     */
    validations?: { [key: string]: { [key: string]: string; }; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof UpAttribute
     */
    annotations?: { [key: string]: string; };
    /**
     * 
     * @type {UpAttributeRequired}
     * @memberof UpAttribute
     */
    required?: UpAttributeRequired;
    /**
     * 
     * @type {UpAttributePermissions}
     * @memberof UpAttribute
     */
    permissions?: UpAttributePermissions;
    /**
     * 
     * @type {UpAttributeSelector}
     * @memberof UpAttribute
     */
    selector?: UpAttributeSelector;
    /**
     * 
     * @type {string}
     * @memberof UpAttribute
     */
    group?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpAttribute
     */
    multivalued?: boolean;
}


