// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpAttributePermissions
 */
export interface UpAttributePermissions {
    /**
     * 
     * @type {Array<string>}
     * @memberof UpAttributePermissions
     */
    view?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpAttributePermissions
     */
    edit?: Array<string>;
}


