// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UnmanagedAttributePolicy } from './unmanaged-attribute-policy';
import { UpAttribute } from './up-attribute';
import { UpGroup } from './up-group';

/**
 * 
 * @export
 * @interface UpConfig
 */
export interface UpConfig {
    /**
     * 
     * @type {Array<UpAttribute>}
     * @memberof UpConfig
     */
    attributes?: Array<UpAttribute>;
    /**
     * 
     * @type {Array<UpGroup>}
     * @memberof UpConfig
     */
    groups?: Array<UpGroup>;
    /**
     * 
     * @type {UnmanagedAttributePolicy}
     * @memberof UpConfig
     */
    unmanagedAttributePolicy?: UnmanagedAttributePolicy;
}


