// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpGroup
 */
export interface UpGroup {
    /**
     * 
     * @type {string}
     * @memberof UpGroup
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpGroup
     */
    displayHeader?: string;
    /**
     * 
     * @type {string}
     * @memberof UpGroup
     */
    displayDescription?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof UpGroup
     */
    annotations?: { [key: string]: string; };
}


