// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserReqSchema } from './user-req-schema';

/**
 * UserImportReqSchema
 * @export
 * @interface UserImportReqSchema
 */
export interface UserImportReqSchema {
    /**
     * Count
     * @type {number}
     * @memberof UserImportReqSchema
     */
    count: number;
    /**
     * Data
     * @type {Array<UserReqSchema>}
     * @memberof UserImportReqSchema
     */
    data: Array<UserReqSchema>;
}


