// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * UserReqSchema
 * @export
 * @interface UserReqSchema
 */
export interface UserReqSchema {
    /**
     * Fullname
     * @type {string}
     * @memberof UserReqSchema
     */
    fullname: string;
    /**
     * Email
     * @type {string}
     * @memberof UserReqSchema
     */
    email: string;
    /**
     * Mobile
     * @type {string}
     * @memberof UserReqSchema
     */
    mobile: string;
    /**
     * Active
     * @type {boolean}
     * @memberof UserReqSchema
     */
    active?: boolean;
    /**
     * Password
     * @type {string}
     * @memberof UserReqSchema
     */
    password: string;
}


