// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserSessionRepresentation
 */
export interface UserSessionRepresentation {
    /**
     * 
     * @type {string}
     * @memberof UserSessionRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSessionRepresentation
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSessionRepresentation
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSessionRepresentation
     */
    ipAddress?: string;
    /**
     * 
     * @type {number}
     * @memberof UserSessionRepresentation
     */
    start?: number;
    /**
     * 
     * @type {number}
     * @memberof UserSessionRepresentation
     */
    lastAccess?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserSessionRepresentation
     */
    rememberMe?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof UserSessionRepresentation
     */
    clients?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof UserSessionRepresentation
     */
    transientUser?: boolean;
}


