// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserProfileAttributeMetadata
 */
export interface UserProfileAttributeMetadata {
    /**
     * 
     * @type {string}
     * @memberof UserProfileAttributeMetadata
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileAttributeMetadata
     */
    displayName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfileAttributeMetadata
     */
    required?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfileAttributeMetadata
     */
    readOnly?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof UserProfileAttributeMetadata
     */
    annotations?: { [key: string]: string; };
    /**
     * 
     * @type {{ [key: string]: { [key: string]: string; }; }}
     * @memberof UserProfileAttributeMetadata
     */
    validators?: { [key: string]: { [key: string]: string; }; };
    /**
     * 
     * @type {string}
     * @memberof UserProfileAttributeMetadata
     */
    group?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfileAttributeMetadata
     */
    multivalued?: boolean;
}


