// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * UserSignupResSchema
 * @export
 * @interface UserSignupResSchema
 */
export interface UserSignupResSchema {
    /**
     * Fullname
     * @type {string}
     * @memberof UserSignupResSchema
     */
    fullname: string;
    /**
     * Email
     * @type {string}
     * @memberof UserSignupResSchema
     */
    email: string;
    /**
     * Mobile
     * @type {string}
     * @memberof UserSignupResSchema
     */
    mobile: string;
    /**
     * Id
     * @type {string}
     * @memberof UserSignupResSchema
     */
    id: string;
    /**
     * Created Ts
     * @type {string}
     * @memberof UserSignupResSchema
     */
    created_ts: string;
    /**
     * Updated Ts
     * @type {string}
     * @memberof UserSignupResSchema
     */
    updated_ts: string;
}


