// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserProfileAttributeGroupMetadata } from './user-profile-attribute-group-metadata';
import { UserProfileAttributeMetadata } from './user-profile-attribute-metadata';

/**
 * 
 * @export
 * @interface UserProfileMetadata
 */
export interface UserProfileMetadata {
    /**
     * 
     * @type {Array<UserProfileAttributeMetadata>}
     * @memberof UserProfileMetadata
     */
    attributes?: Array<UserProfileAttributeMetadata>;
    /**
     * 
     * @type {Array<UserProfileAttributeGroupMetadata>}
     * @memberof UserProfileMetadata
     */
    groups?: Array<UserProfileAttributeGroupMetadata>;
}


