// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';

/**
 * UserResSchema
 * @export
 * @interface UserResSchema
 */
export interface UserResSchema {
    /**
     * Fullname
     * @type {string}
     * @memberof UserResSchema
     */
    fullname: string;
    /**
     * Email
     * @type {string}
     * @memberof UserResSchema
     */
    email: string;
    /**
     * Mobile
     * @type {string}
     * @memberof UserResSchema
     */
    mobile: string;
    /**
     * Active
     * @type {boolean}
     * @memberof UserResSchema
     */
    active?: boolean;
    /**
     * Id
     * @type {string}
     * @memberof UserResSchema
     */
    id: string;
    /**
     * Tenant Id
     * @type {string | Null}
     * @memberof UserResSchema
     */
    tenant_id?: string | Null;
    /**
     * Created Ts
     * @type {string}
     * @memberof UserResSchema
     */
    created_ts: string;
    /**
     * Updated Ts
     * @type {string}
     * @memberof UserResSchema
     */
    updated_ts: string;
}


