// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ValidationError
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * Location
     * @type {Array<string | number>}
     * @memberof ValidationError
     */
    loc: Array<string | number>;
    /**
     * Message
     * @type {string}
     * @memberof ValidationError
     */
    msg: string;
    /**
     * Error Type
     * @type {string}
     * @memberof ValidationError
     */
    type: string;
}


