// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VendorReqSchema } from './vendor-req-schema';

/**
 * VendorImportReqSchema
 * @export
 * @interface VendorImportReqSchema
 */
export interface VendorImportReqSchema {
    /**
     * Count
     * @type {number}
     * @memberof VendorImportReqSchema
     */
    count: number;
    /**
     * Data
     * @type {Array<VendorReqSchema>}
     * @memberof VendorImportReqSchema
     */
    data: Array<VendorReqSchema>;
}


