// tslint:disable
/**
 * My Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { VendorResSchema } from './vendor-res-schema';

/**
 * VendorExportResSchema
 * @export
 * @interface VendorExportResSchema
 */
export interface VendorExportResSchema {
    /**
     * Count
     * @type {number}
     * @memberof VendorExportResSchema
     */
    count: number;
    /**
     * Data
     * @type {Array<VendorResSchema>}
     * @memberof VendorExportResSchema
     */
    data: Array<VendorResSchema>;
}


